{"report": {"environment": {"Python": "3.11.5", "Platform": "macOS-13.3.1-arm64-arm-64bit"}, "tests": [{"name": "test_API_automation.py::test_create_new_user", "duration": 1.4975178348831832, "run_index": 0, "setup": {"name": "setup", "duration": 0.748440416995436, "outcome": "passed", "stderr": "DEBUG:faker.factory:Looking for locale `en_US` in provider `faker.providers.address`.\nDEBUG:faker.factory:Provider `faker.providers.address` has been localized to `en_US`.\nDEBUG:faker.factory:Looking for locale `en_US` in provider `faker.providers.automotive`.\nDEBUG:faker.factory:Provider `faker.providers.automotive` has been localized to `en_US`.\nDEBUG:faker.factory:Looking for locale `en_US` in provider `faker.providers.bank`.\nDEBUG:faker.factory:Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.\nDEBUG:faker.factory:Looking for locale `en_US` in provider `faker.providers.barcode`.\nDEBUG:faker.factory:Provider `faker.providers.barcode` has been localized to `en_US`.\nDEBUG:faker.factory:Looking for locale `en_US` in provider `faker.providers.color`.\nDEBUG:faker.factory:Provider `faker.providers.color` has been localized to `en_US`.\nDEBUG:faker.factory:Looking for locale `en_US` in provider `faker.providers.company`.\nDEBUG:faker.factory:Provider `faker.providers.company` has been localized to `en_US`.\nDEBUG:faker.factory:Looking for locale `en_US` in provider `faker.providers.credit_card`.\nDEBUG:faker.factory:Provider `faker.providers.credit_card` has been localized to `en_US`.\nDEBUG:faker.factory:Looking for locale `en_US` in provider `faker.providers.currency`.\nDEBUG:faker.factory:Provider `faker.providers.currency` has been localized to `en_US`.\nDEBUG:faker.factory:Looking for locale `en_US` in provider `faker.providers.date_time`.\nDEBUG:faker.factory:Provider `faker.providers.date_time` has been localized to `en_US`.\nDEBUG:faker.factory:Provider `faker.providers.emoji` does not feature localization. Specified locale `en_US` is not utilized for this provider.\nDEBUG:faker.factory:Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.\nDEBUG:faker.factory:Looking for locale `en_US` in provider `faker.providers.geo`.\nDEBUG:faker.factory:Provider `faker.providers.geo` has been localized to `en_US`.\nDEBUG:faker.factory:Looking for locale `en_US` in provider `faker.providers.internet`.\nDEBUG:faker.factory:Provider `faker.providers.internet` has been localized to `en_US`.\nDEBUG:faker.factory:Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.\nDEBUG:faker.factory:Looking for locale `en_US` in provider `faker.providers.job`.\nDEBUG:faker.factory:Provider `faker.providers.job` has been localized to `en_US`.\nDEBUG:faker.factory:Looking for locale `en_US` in provider `faker.providers.lorem`.\nDEBUG:faker.factory:Provider `faker.providers.lorem` has been localized to `en_US`.\nDEBUG:faker.factory:Looking for locale `en_US` in provider `faker.providers.misc`.\nDEBUG:faker.factory:Provider `faker.providers.misc` has been localized to `en_US`.\nDEBUG:faker.factory:Looking for locale `en_US` in provider `faker.providers.passport`.\nDEBUG:faker.factory:Provider `faker.providers.passport` has been localized to `en_US`.\nDEBUG:faker.factory:Looking for locale `en_US` in provider `faker.providers.person`.\nDEBUG:faker.factory:Provider `faker.providers.person` has been localized to `en_US`.\nDEBUG:faker.factory:Looking for locale `en_US` in provider `faker.providers.phone_number`.\nDEBUG:faker.factory:Provider `faker.providers.phone_number` has been localized to `en_US`.\nDEBUG:faker.factory:Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.\nDEBUG:faker.factory:Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.\nDEBUG:faker.factory:Provider `faker.providers.sbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.\nDEBUG:faker.factory:Looking for locale `en_US` in provider `faker.providers.ssn`.\nDEBUG:faker.factory:Provider `faker.providers.ssn` has been localized to `en_US`.\nDEBUG:faker.factory:Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.\nDEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG:urllib3.connectionpool:https://gorest.co.in:443 \"POST /public/v2/users/ HTTP/1.1\" 201 None\nDEBUG:conftest:User created with ID: 5203226\nDEBUG:conftest:User data: {'id': 5203226, 'name': 'Heidi Dickerson', 'email': 'bford@example.org', 'gender': 'female', 'status': 'active'}\n", "log": "DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.address`.\nDEBUG    faker.factory:factory.py:95 Provider `faker.providers.address` has been localized to `en_US`.\nDEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.automotive`.\nDEBUG    faker.factory:factory.py:95 Provider `faker.providers.automotive` has been localized to `en_US`.\nDEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.bank`.\nDEBUG    faker.factory:factory.py:86 Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.\nDEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.barcode`.\nDEBUG    faker.factory:factory.py:95 Provider `faker.providers.barcode` has been localized to `en_US`.\nDEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.color`.\nDEBUG    faker.factory:factory.py:95 Provider `faker.providers.color` has been localized to `en_US`.\nDEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.company`.\nDEBUG    faker.factory:factory.py:95 Provider `faker.providers.company` has been localized to `en_US`.\nDEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.credit_card`.\nDEBUG    faker.factory:factory.py:95 Provider `faker.providers.credit_card` has been localized to `en_US`.\nDEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.currency`.\nDEBUG    faker.factory:factory.py:95 Provider `faker.providers.currency` has been localized to `en_US`.\nDEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.date_time`.\nDEBUG    faker.factory:factory.py:95 Provider `faker.providers.date_time` has been localized to `en_US`.\nDEBUG    faker.factory:factory.py:106 Provider `faker.providers.emoji` does not feature localization. Specified locale `en_US` is not utilized for this provider.\nDEBUG    faker.factory:factory.py:106 Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.\nDEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.geo`.\nDEBUG    faker.factory:factory.py:95 Provider `faker.providers.geo` has been localized to `en_US`.\nDEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.internet`.\nDEBUG    faker.factory:factory.py:95 Provider `faker.providers.internet` has been localized to `en_US`.\nDEBUG    faker.factory:factory.py:106 Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.\nDEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.job`.\nDEBUG    faker.factory:factory.py:95 Provider `faker.providers.job` has been localized to `en_US`.\nDEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.lorem`.\nDEBUG    faker.factory:factory.py:95 Provider `faker.providers.lorem` has been localized to `en_US`.\nDEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.misc`.\nDEBUG    faker.factory:factory.py:95 Provider `faker.providers.misc` has been localized to `en_US`.\nDEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.passport`.\nDEBUG    faker.factory:factory.py:95 Provider `faker.providers.passport` has been localized to `en_US`.\nDEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.person`.\nDEBUG    faker.factory:factory.py:95 Provider `faker.providers.person` has been localized to `en_US`.\nDEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.phone_number`.\nDEBUG    faker.factory:factory.py:95 Provider `faker.providers.phone_number` has been localized to `en_US`.\nDEBUG    faker.factory:factory.py:106 Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.\nDEBUG    faker.factory:factory.py:106 Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.\nDEBUG    faker.factory:factory.py:106 Provider `faker.providers.sbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.\nDEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.ssn`.\nDEBUG    faker.factory:factory.py:95 Provider `faker.providers.ssn` has been localized to `en_US`.\nDEBUG    faker.factory:factory.py:106 Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.\nDEBUG    urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG    urllib3.connectionpool:connectionpool.py:452 https://gorest.co.in:443 \"POST /public/v2/users/ HTTP/1.1\" 201 None\nDEBUG    conftest:conftest.py:65 User created with ID: 5203226\nDEBUG    conftest:conftest.py:66 User data: {'id': 5203226, 'name': 'Heidi Dickerson', 'email': 'bford@example.org', 'gender': 'female', 'status': 'active'}"}, "call": {"name": "call", "duration": 0.000459916889667511, "outcome": "passed", "stderr": "INFO:root:User Data:\nINFO:root:[\n    5203226,\n    {\n        \"id\": 5203226,\n        \"name\": \"Heidi Dickerson\",\n        \"email\": \"bford@example.org\",\n        \"gender\": \"female\",\n        \"status\": \"active\"\n    }\n]\n", "log": "INFO     root:test_API_automation.py:24 User Data:\nINFO     root:test_API_automation.py:25 [\n    5203226,\n    {\n        \"id\": 5203226,\n        \"name\": \"Heidi Dickerson\",\n        \"email\": \"bford@example.org\",\n        \"gender\": \"female\",\n        \"status\": \"active\"\n    }\n]"}, "teardown": {"name": "teardown", "duration": 0.00017708400264382362, "outcome": "passed"}, "outcome": "passed"}, {"name": "test_API_automation.py::test_confirm_the_new_user_created", "duration": 0.8080250429920852, "run_index": 1, "setup": {"name": "setup", "duration": 0.4036904589738697, "outcome": "passed", "stderr": "DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG:urllib3.connectionpool:https://gorest.co.in:443 \"GET /public/v2/users//5203226 HTTP/1.1\" 200 None\nDEBUG:conftest:Validating user with ID: 5203226\nDEBUG:conftest:Response data: {'id': 5203226, 'name': 'Heidi Dickerson', 'email': 'bford@example.org', 'gender': 'female', 'status': 'active'}\n", "log": "DEBUG    urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG    urllib3.connectionpool:connectionpool.py:452 https://gorest.co.in:443 \"GET /public/v2/users//5203226 HTTP/1.1\" 200 None\nDEBUG    conftest:conftest.py:80 Validating user with ID: 5203226\nDEBUG    conftest:conftest.py:81 Response data: {'id': 5203226, 'name': 'Heidi Dickerson', 'email': 'bford@example.org', 'gender': 'female', 'status': 'active'}"}, "call": {"name": "call", "duration": 0.00035850005224347115, "outcome": "passed"}, "teardown": {"name": "teardown", "duration": 0.00028562499210238457, "outcome": "passed"}, "outcome": "passed"}, {"name": "test_API_automation.py::test_create_todo_for_user", "duration": 0.8122060000896454, "run_index": 2, "setup": {"name": "setup", "duration": 0.4058407919947058, "outcome": "passed", "stderr": "DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG:urllib3.connectionpool:https://gorest.co.in:443 \"POST /public/v2/users/5203226/todos HTTP/1.1\" 201 None\nDEBUG:conftest:Verifying deleted user with ID: 5203226\nDEBUG:conftest:Response status code: 201\nDEBUG:conftest:Response data: {\"id\":27899,\"user_id\":5203226,\"title\":\"Region PM miss dark animal.\",\"due_on\":null,\"status\":\"pending\"}\n", "log": "DEBUG    urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG    urllib3.connectionpool:connectionpool.py:452 https://gorest.co.in:443 \"POST /public/v2/users/5203226/todos HTTP/1.1\" 201 None\nDEBUG    conftest:conftest.py:173 Verifying deleted user with ID: 5203226\nDEBUG    conftest:conftest.py:174 Response status code: 201\nDEBUG    conftest:conftest.py:175 Response data: {\"id\":27899,\"user_id\":5203226,\"title\":\"Region PM miss dark animal.\",\"due_on\":null,\"status\":\"pending\"}"}, "call": {"name": "call", "duration": 0.000278332969173789, "outcome": "passed"}, "teardown": {"name": "teardown", "duration": 0.00024608313106000423, "outcome": "passed"}, "outcome": "passed"}, {"name": "test_API_automation.py::test_confirm_user_todos_created", "duration": 2.2461599179077893, "run_index": 3, "setup": {"name": "setup", "duration": 1.1227899589575827, "outcome": "passed", "stderr": "DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG:urllib3.connectionpool:https://gorest.co.in:443 \"POST /public/v2/users/5203226/todos HTTP/1.1\" 201 None\nDEBUG:conftest:Verifying deleted user with ID: 5203226\nDEBUG:conftest:Response status code: 201\nDEBUG:conftest:Response data: {\"id\":27900,\"user_id\":5203226,\"title\":\"To admit knowledge class others very.\",\"due_on\":null,\"status\":\"pending\"}\nDEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG:urllib3.connectionpool:https://gorest.co.in:443 \"GET /public/v2/users//5203226/todos HTTP/1.1\" 200 None\nDEBUG:conftest:Getting user todos for ID: 5203226\nDEBUG:conftest:Response status code: 200\nDEBUG:conftest:Response data: [{\"id\":27900,\"user_id\":5203226,\"title\":\"To admit knowledge class others very.\",\"due_on\":null,\"status\":\"pending\"},{\"id\":27899,\"user_id\":5203226,\"title\":\"Region PM miss dark animal.\",\"due_on\":null,\"status\":\"pending\"}]\n", "log": "DEBUG    urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG    urllib3.connectionpool:connectionpool.py:452 https://gorest.co.in:443 \"POST /public/v2/users/5203226/todos HTTP/1.1\" 201 None\nDEBUG    conftest:conftest.py:173 Verifying deleted user with ID: 5203226\nDEBUG    conftest:conftest.py:174 Response status code: 201\nDEBUG    conftest:conftest.py:175 Response data: {\"id\":27900,\"user_id\":5203226,\"title\":\"To admit knowledge class others very.\",\"due_on\":null,\"status\":\"pending\"}\nDEBUG    urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG    urllib3.connectionpool:connectionpool.py:452 https://gorest.co.in:443 \"GET /public/v2/users//5203226/todos HTTP/1.1\" 200 None\nDEBUG    conftest:conftest.py:186 Getting user todos for ID: 5203226\nDEBUG    conftest:conftest.py:187 Response status code: 200\nDEBUG    conftest:conftest.py:188 Response data: [{\"id\":27900,\"user_id\":5203226,\"title\":\"To admit knowledge class others very.\",\"due_on\":null,\"status\":\"pending\"},{\"id\":27899,\"user_id\":5203226,\"title\":\"Region PM miss dark animal.\",\"due_on\":null,\"status\":\"pending\"}]"}, "call": {"name": "call", "duration": 0.00031349994242191315, "outcome": "passed"}, "teardown": {"name": "teardown", "duration": 0.00026650005020201206, "outcome": "passed"}, "outcome": "passed"}, {"name": "test_API_automation.py::test_update_user_credentials", "duration": 0.8106703346129507, "run_index": 4, "setup": {"name": "setup", "duration": 0.4050758338999003, "outcome": "passed", "stderr": "DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG:urllib3.connectionpool:https://gorest.co.in:443 \"PATCH /public/v2/users//5203226 HTTP/1.1\" 200 None\nDEBUG:conftest:User created with ID: 5203226\nDEBUG:conftest:User data: {'email': 'ilee@example.net', 'name': 'Kelly Davis', 'gender': 'female', 'status': 'active', 'id': 5203226}\n", "log": "DEBUG    urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG    urllib3.connectionpool:connectionpool.py:452 https://gorest.co.in:443 \"PATCH /public/v2/users//5203226 HTTP/1.1\" 200 None\nDEBUG    conftest:conftest.py:105 User created with ID: 5203226\nDEBUG    conftest:conftest.py:106 User data: {'email': 'ilee@example.net', 'name': 'Kelly Davis', 'gender': 'female', 'status': 'active', 'id': 5203226}"}, "call": {"name": "call", "duration": 0.00032545882277190685, "outcome": "passed"}, "teardown": {"name": "teardown", "duration": 0.0001932079903781414, "outcome": "passed"}, "outcome": "passed"}, {"name": "test_API_automation.py::test_confirm_users_credentials_updated", "duration": 0.8126195000950247, "run_index": 5, "setup": {"name": "setup", "duration": 0.40593912499025464, "outcome": "passed", "stderr": "DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG:urllib3.connectionpool:https://gorest.co.in:443 \"GET /public/v2/users//5203226 HTTP/1.1\" 200 None\nDEBUG:conftest:User created with ID: 5203226\nDEBUG:conftest:User data: {'id': 5203226, 'name': 'Kelly Davis', 'email': 'ilee@example.net', 'gender': 'female', 'status': 'active'}\n", "log": "DEBUG    urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG    urllib3.connectionpool:connectionpool.py:452 https://gorest.co.in:443 \"GET /public/v2/users//5203226 HTTP/1.1\" 200 None\nDEBUG    conftest:conftest.py:119 User created with ID: 5203226\nDEBUG    conftest:conftest.py:120 User data: {'id': 5203226, 'name': 'Kelly Davis', 'email': 'ilee@example.net', 'gender': 'female', 'status': 'active'}"}, "call": {"name": "call", "duration": 0.00035087508149445057, "outcome": "passed"}, "teardown": {"name": "teardown", "duration": 0.0003903750330209732, "outcome": "passed"}, "outcome": "passed"}, {"name": "test_API_automation.py::test_delete_user", "duration": 0.8083382081240416, "run_index": 6, "setup": {"name": "setup", "duration": 0.40385220805183053, "outcome": "passed", "stderr": "DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG:urllib3.connectionpool:https://gorest.co.in:443 \"DELETE /public/v2/users//5203226 HTTP/1.1\" 204 0\nDEBUG:conftest:Deleting user with ID: 5203226\nDEBUG:conftest:Response status code: 204\nDEBUG:conftest:Response data: \n", "log": "DEBUG    urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG    urllib3.connectionpool:connectionpool.py:452 https://gorest.co.in:443 \"DELETE /public/v2/users//5203226 HTTP/1.1\" 204 0\nDEBUG    conftest:conftest.py:130 Deleting user with ID: 5203226\nDEBUG    conftest:conftest.py:131 Response status code: 204\nDEBUG    conftest:conftest.py:132 Response data:"}, "call": {"name": "call", "duration": 0.000330084003508091, "outcome": "passed"}, "teardown": {"name": "teardown", "duration": 0.000303708016872406, "outcome": "passed"}, "outcome": "passed"}, {"name": "test_API_automation.py::test_verify_deleted_user", "duration": 0.8050771260168403, "run_index": 7, "setup": {"name": "setup", "duration": 0.4024099591188133, "outcome": "passed", "stderr": "DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG:urllib3.connectionpool:https://gorest.co.in:443 \"GET /public/v2/users//5203226 HTTP/1.1\" 404 None\nDEBUG:conftest:Verifying user with ID: 5203226\nDEBUG:conftest:Response status code: 404\nDEBUG:conftest:Response data: {\"message\":\"Resource not found\"}\n", "log": "DEBUG    urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG    urllib3.connectionpool:connectionpool.py:452 https://gorest.co.in:443 \"GET /public/v2/users//5203226 HTTP/1.1\" 404 None\nDEBUG    conftest:conftest.py:141 Verifying user with ID: 5203226\nDEBUG    conftest:conftest.py:142 Response status code: 404\nDEBUG    conftest:conftest.py:143 Response data: {\"message\":\"Resource not found\"}"}, "call": {"name": "call", "duration": 0.0001421249471604824, "outcome": "passed"}, "teardown": {"name": "teardown", "duration": 0.00011508283205330372, "outcome": "passed"}, "outcome": "passed"}, {"name": "test_API_automation.py::test_negative_invalid_patch_request", "duration": 0.8221650845371187, "run_index": 8, "setup": {"name": "setup", "duration": 0.4106600421946496, "outcome": "passed", "stderr": "DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG:urllib3.connectionpool:https://gorest.co.in:443 \"PATCH /public/v2/users//5203226 HTTP/1.1\" 404 None\nDEBUG:conftest:Invalid PATCH request for user ID: 5203226\nDEBUG:conftest:Response status code: 404\nDEBUG:conftest:Response data: {\"message\":\"Resource not found\"}\n", "log": "DEBUG    urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): gorest.co.in:443\nDEBUG    urllib3.connectionpool:connectionpool.py:452 https://gorest.co.in:443 \"PATCH /public/v2/users//5203226 HTTP/1.1\" 404 None\nDEBUG    conftest:conftest.py:206 Invalid PATCH request for user ID: 5203226\nDEBUG    conftest:conftest.py:207 Response status code: 404\nDEBUG    conftest:conftest.py:208 Response data: {\"message\":\"Resource not found\"}"}, "call": {"name": "call", "duration": 0.00025566713884472847, "outcome": "passed"}, "teardown": {"name": "teardown", "duration": 0.0005893330089747906, "outcome": "passed"}, "outcome": "passed"}], "summary": {"passed": 9, "num_tests": 9, "duration": 4.758602857589722}, "created_at": "2023-09-25 14:39:15.949808"}}